# Generated by Django 4.2.27 on 2026-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_studied', models.IntegerField()),
                ('previous_scores', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('sleep_hours', models.IntegerField()),
                ('sample_papers', models.IntegerField()),
                ('predicted_performance_index', models.FloatField()),
                ('advice', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
